### PR TITLE
Fixes: change to map, remove incompat with capeling, add github action

### PR DESCRIPTION
**Pull request by RayDeeUx**
oh yeah and make it crossplatform as well but that's not a big deal or anything

### CODE REVIEW

**Comment by PetitFrapo** [comment]
oh wow thanks! i guess i don't have enough c++ experience to optimize my code haha
thank you so much for the automated build i didn't even know you could do that!
i don't know about the changes to the description though, will look a bit more into that
where do you want me to credit you?

**Comment by PetitFrapo** [comment]
uhhh my previous update has a bug so i'll merge this one and credit you real quick in about.md and the github readme

**Comment by PetitFrapo** [comment]
could you explain to me real quick how to use github actions? never did before...

**Comment by RayDeeUx** [comment]
> where do you want me to credit you?

about.md is fine

**Pull request merged**
